### ISSUE TITLE
切换下一视频后，视频倍速及显示未更新

### ISSUE THREAD

**Issue by calleu** [Vikiboss/BaidupanPlaySpeedControl#1]
1.4版本，如果鼠标点击页面“其他视频”下切换网盘其他视频，但未重新刷新页面时，倍速不能保留原设定倍速，且倍速显示未更新，仍显示原设定的倍速。建议倍速显示可以在切换视频时刷新显示，另外是否可设置可选锁定倍速

**Comment by vikiboss** [comment]
OK  下一个版本加入缓存读取(可选项) 等我先忙完考试
