### ISSUE TITLE
使用插件视频直接不加载了

### ISSUE THREAD

**Issue by ccclly** [Vikiboss/BaidupanPlaySpeedControl#4]

**Comment by vikiboss** [comment]
注意 readme 描述

> 请注意，由于百度网盘桌面端的更新，脚本在2021年4月就已失效，如仍有倍速播放需求，可在b站寻找[相关教程](https://search.bilibili.com/all?keyword=%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E5%80%8D%E9%80%9F%E6%92%AD%E6%94%BE)。
